### ISSUE TITLE
Synced lyrics unavailable for Chinese songs

### ISSUE THREAD

**Issue by hq6** [youkaclub/youka-desktop#3]
I'm not sure whether this is a bug or missing feature, but I'm filing it as an issue because youka's tagline seems to be for any language.

I searched for "Big Fish Zhou Shen" and clocked on the first result. It seems to be able to separate instrumental from voice, but it says "synced lyrics are unavailable".

**Comment by youkaclub** [comment]
Hello @hq6, it possibly happened because youka can't find lyrics in the currently supported lyrics providers (https://github.com/youkaclub/youka-lyrics/issues/1).
You may suggest a new lyrics provider (website) for Chinese songs, I'll try to add it in the next release.
If you are a developer, please consider to contribute by implement it and open push request.

**Comment by ericwong3** [comment]
There are two lyrics provider I have used previously indirectly. 


One is TTLyrics (千千歌词), formerly a part of TTPlayer. Their API is open for invocation. However [their doc](http://docs.ttlyrics.com/440699) is Chinese only. I can translate it for you, no problem.

Pro: Given the number of Chinese netizens, you can find virtually any song
Con: Crowdsourced and not categorized by song means each song has multiple lyrics available*.
Con: The API is quite slow, a quick test just now takes 10s to load.

\* i.e. the server returns multiple available lyrics for same song title.


Another one is Mojim (魔鏡歌詞網), the list is quite comprehensive as well (Chinese and Cantonese included). It is Taiwan-based so I assume songs from Taiwan are fully covered as well. However, they have no API to provide, they have a "Collaboration proposal" form on their site though, might give a try.

**Comment by youkaclub** [comment]
thanks @ericwong3, I've added TTLyrics  and Mojim to the list https://github.com/youkaclub/youka-lyrics/issues/1.
the only weird thing is that you can search only by singer or by song, not both in the same time. it's much harder to find lyrics in that way automatically because youtube title is unstructured.

**Comment by ericwong3** [comment]
btw for some songs actually the uploader putted lyrics in youtube's CC, [The Weeknd - Starboy ft. Daft Punk (Official Video)](https://www.youtube.com/watch?v=34Na4j8AVgA) is an example. But I am not sure if it can be retrieved through API, and how it fits into youka-desktop (as the searching is done by passing song name to youka-lyrics)

**Comment by youkaclub** [comment]
@ericwong3 extract captions from youtube is in my todo list as well..

**Comment by youkaclub** [comment]
@hq6 I've added few Chinese lyrics providers, it should work from now, but I don't speak Chinese so it's hard for me to test the sync.

**Comment by hq6** [comment]
Much appreciated, will give it a try!
